server:
  port: 8010
spring:
  application:
    name: order
  datasource:
    name: orderingSystem
    url: jdbc:mysql://javatechdb.c0supn9oemkl.us-east-2.rds.amazonaws.com:3306/orderingsystem?useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345678
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.jiaying.entity
